export const listingEngagement = {
  id: "c0f13791-b467-4d6a-8fb8-be6a02760e8a",
  dispoListingId: "3a67ea0f-c5ae-4e9e-a37b-a2cb4d454d32",
  showings: 2,
  views: 0,
  saves: 2,
  createdAt: "2024-05-27T16:45:15.305Z",
  updatedAt: "2024-05-27T16:45:15.305Z",
  discardedAt: null,
  syndicationLastCollected: "2024-05-27",
  syndicationLink: "eos umerus verbum",
};

export const commissionsAndExpenses = {
  commissions: {
    listingSideCommissionType: "flat_fee",
    listingSideCommissionPercentage: null,
    listingSideFlatFee: "3.0",
    buyingSideCommissionType: "flat_fee",
    buyingSideCommissionPercentage: null,
    buyingSideFlatFee: "0.0",
    commissionsFinalizedDate: "2024-02-15",
    notes: "",
    listingSideGrossCommission: "3.0",
    listingSideTotalCommissionReduction: "9.0",
    listingSideNetCommission: "-6.0",
    buyingSideGrossCommission: "0.0",
    totalReimbursableExpensesOnHud: "0.0",
    totalCommissionPercentage: "0.0",
    totalCommissionAmount: "3.0",
    // reductionsAttributes: [[Object], [Object], [Object], [Object]],
  },
  options: {
    commission: {
      buyingSideCommissionType: [
        { value: "percentage", label: "Percentage" },
        { value: "flat_fee", label: "Flat Fee" },
      ],
      listingSideCommissionType: [
        { value: "percentage", label: "Percentage" },
        { value: "flat_fee", label: "Flat Fee" },
      ],
    },
    reductionsAttributes: {
      listingSideCommissionReductionType: [
        { value: "hud_concession", label: "HUD Concession" },
        { value: "technology_fee", label: "Technology Fee" },
        { value: "referral_fee", label: "Referral Fee" },
      ],
    },
  },
};

export const propertyDetails = {
  opportunity: {
    marketId: 7,
    streetAddress: "271 Commercial Street",
    city: "Port Aron",
    state: "Texas",
    zip: "32149",
    county: "South Glamorgan",
    subdivision: "Kent",
    apn: "3",
    legalDescription: "aurum ulciscor accusator tripudio angelus",
    propertyType: "townhouse",
    marketName: "Atlanta",
    propertyTypeLabel: "Townhouse",
    propertyDetailAttributes: {
      beds: 5,
      fullBaths: 4,
      halfBaths: 2,
      lotSqft: 4,
      yearBuilt: 2010,
      quarterBaths: 2,
      threeQuarterBaths: 1,
      buildingSqft: 2,
      pool: "no",
      stories: 2,
      winterized: false,
    },
    hoaAttributes: {
      status: "unknown",
      fee: "0.0",
      feeFrequency: "quarterly",
      name: "corrupti admitto",
      reviewed: "yes",
      phoneNumber: "(202) 967 - 4871",
      website: null,
      statusLabel: "Unknown",
      feeFrequencyLabel: "Quarterly",
      reviewedLabel: "Yes",
    },
    hoasAttributes: [
      {
        status: "unknown",
        fee: "0.0",
        feeFrequency: "quarterly",
        name: "corrupti admitto",
        reviewed: "yes",
        phoneNumber: "(202) 967 - 4871",
        website: null,
        id: "83b6f97b-cd6a-469a-af35-26bea0c0512b",
      },
    ],
    utilityAttributes: {
      gasUtility: "active",
      electricUtility: "inactive",
      waterUtility: "tbd",
      specialUtilityDistrictName: "Lincolnshire",
      specialUtilityDistrictFee: "2.0",
      specialUtilityDistrictFeeFrequency: "annually",
      gasUtilityLabel: "Active",
      waterUtilityLabel: "TBD",
      electricUtilityLabel: "Inactive",
      specialUtilityDistrictFeeFrequencyLabel: "Annually",
    },
  },
  options: {
    opportunity: {
      propertyType: [
        { value: "single_family", label: "Single family" },
        { value: "not_specified", label: "Not specified" },
        { value: "townhouse", label: "Townhouse" },
        { value: "apartment", label: "Apartment" },
        { value: "commercial", label: "Commercial" },
        { value: "condo", label: "Condo" },
        { value: "duplex", label: "Duplex" },
        { value: "farm", label: "Farm" },
        { value: "land", label: "Land" },
        { value: "manufactured", label: "Manufactured" },
        { value: "mobile", label: "Mobile" },
        { value: "multi_unit", label: "Multi unit" },
        { value: "rentals", label: "Rentals" },
        { value: "other", label: "Other" },
      ],
    },
    hoaAttributes: {
      status: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      feeFrequency: [
        { label: "quartly", value: "quartly" },
        { label: "Monthly", value: "monthly" },
      ],
      reviewed: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
    },
    utilityAttributes: {
      gasUtility: [
        { label: "Active", value: "active" },
        { label: "Inactive", value: "inactive" },
        { label: "TBD", value: "tbd" },
      ],
      waterUtility: [
        { label: "Active", value: "active" },
        { label: "Inactive", value: "inactive" },
        { label: "TBD", value: "tbd" },
      ],
      electricUtility: [
        { label: "Active", value: "active" },
        { label: "Inactive", value: "inactive" },
        { label: "TBD", value: "tbd" },
      ],
      specialUtilityDistrictFeeFrequency: [
        { label: "quartly", value: "quartly" },
        { label: "Monthly", value: "monthly" },
      ],
    },
  },
};
