export const listingEngagement = {
  id: "c0f13791-b467-4d6a-8fb8-be6a02760e8a",
  dispoListingId: "3a67ea0f-c5ae-4e9e-a37b-a2cb4d454d32",
  showings: 2,
  views: 0,
  saves: 2,
  createdAt: "2024-05-27T16:45:15.305Z",
  updatedAt: "2024-05-27T16:45:15.305Z",
  discardedAt: null,
  syndicationLastCollected: "2024-05-27",
  syndicationLink: "eos umerus verbum",
};

export const commissionsAndExpenses = {
  commissions: {
    listingSideCommissionType: "flat_fee",
    listingSideCommissionPercentage: null,
    listingSideFlatFee: "3.0",
    buyingSideCommissionType: "flat_fee",
    buyingSideCommissionPercentage: null,
    buyingSideFlatFee: "0.0",
    commissionsFinalizedDate: "2024-02-15",
    notes: "",
    listingSideGrossCommission: "3.0",
    listingSideTotalCommissionReduction: "9.0",
    listingSideNetCommission: "-6.0",
    buyingSideGrossCommission: "0.0",
    totalReimbursableExpensesOnHud: "0.0",
    totalCommissionPercentage: "0.0",
    totalCommissionAmount: "3.0",
    // reductionsAttributes: [[Object], [Object], [Object], [Object]],
  },
  options: {
    commission: {
      buyingSideCommissionType: [
        { value: "percentage", label: "Percentage" },
        { value: "flat_fee", label: "Flat Fee" },
      ],
      listingSideCommissionType: [
        { value: "percentage", label: "Percentage" },
        { value: "flat_fee", label: "Flat Fee" },
      ],
    },
    reductionsAttributes: {
      listingSideCommissionReductionType: [
        { value: "hud_concession", label: "HUD Concession" },
        { value: "technology_fee", label: "Technology Fee" },
        { value: "referral_fee", label: "Referral Fee" },
      ],
    },
  },
};

export const propertyDetails = {
  opportunity: {
    marketId: 7,
    streetAddress: "271 Commercial Street",
    city: "Port Aron",
    state: "Texas",
    zip: "32149",
    county: "South Glamorgan",
    subdivision: "Kent",
    apn: "3",
    legalDescription: "aurum ulciscor accusator tripudio angelus",
    propertyType: "townhouse",
    marketName: "Atlanta",
    propertyTypeLabel: "Townhouse",
    propertyDetailAttributes: {
      beds: 5,
      fullBaths: 4,
      halfBaths: 2,
      lotSqft: 4,
      yearBuilt: 2010,
      quarterBaths: 2,
      threeQuarterBaths: 1,
      buildingSqft: 2,
      pool: "no",
      stories: 2,
      winterized: false,
    },
    hoaAttributes: {
      status: "unknown",
      fee: "0.0",
      feeFrequency: "quarterly",
      name: "corrupti admitto",
      reviewed: "yes",
      phoneNumber: "(202) 967 - 4871",
      website: null,
      statusLabel: "Unknown",
      feeFrequencyLabel: "Quarterly",
      reviewedLabel: "Yes",
    },
    hoasAttributes: [
      {
        status: "unknown",
        fee: "0.0",
        feeFrequency: "quarterly",
        name: "corrupti admitto",
        reviewed: "yes",
        phoneNumber: "(202) 967 - 4871",
        website: null,
        id: "83b6f97b-cd6a-469a-af35-26bea0c0512b",
      },
    ],
    utilityAttributes: {
      gasUtility: "active",
      electricUtility: "inactive",
      waterUtility: "tbd",
      specialUtilityDistrictName: "Lincolnshire",
      specialUtilityDistrictFee: "2.0",
      specialUtilityDistrictFeeFrequency: "annually",
      gasUtilityLabel: "Active",
      waterUtilityLabel: "TBD",
      electricUtilityLabel: "Inactive",
      specialUtilityDistrictFeeFrequencyLabel: "Annually",
    },
  },
  options: {
    opportunity: {
      propertyType: [
        { value: "single_family", label: "Single family" },
        { value: "not_specified", label: "Not specified" },
        { value: "townhouse", label: "Townhouse" },
        { value: "apartment", label: "Apartment" },
        { value: "commercial", label: "Commercial" },
        { value: "condo", label: "Condo" },
        { value: "duplex", label: "Duplex" },
        { value: "farm", label: "Farm" },
        { value: "land", label: "Land" },
        { value: "manufactured", label: "Manufactured" },
        { value: "mobile", label: "Mobile" },
        { value: "multi_unit", label: "Multi unit" },
        { value: "rentals", label: "Rentals" },
        { value: "other", label: "Other" },
      ],
    },
    hoaAttributes: {
      status: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      feeFrequency: [
        { label: "quartly", value: "quartly" },
        { label: "Monthly", value: "monthly" },
      ],
      reviewed: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
    },
    utilityAttributes: {
      gasUtility: [
        { label: "Active", value: "active" },
        { label: "Inactive", value: "inactive" },
        { label: "TBD", value: "tbd" },
      ],
      waterUtility: [
        { label: "Active", value: "active" },
        { label: "Inactive", value: "inactive" },
        { label: "TBD", value: "tbd" },
      ],
      electricUtility: [
        { label: "Active", value: "active" },
        { label: "Inactive", value: "inactive" },
        { label: "TBD", value: "tbd" },
      ],
      specialUtilityDistrictFeeFrequency: [
        { label: "quartly", value: "quartly" },
        { label: "Monthly", value: "monthly" },
      ],
    },
  },
};

export const listingDetails = {
  id: "3a67ea0f-c5ae-4e9e-a37b-a2cb4d454d32",
  sellerId: "5e70b818-ab86-47d7-ae2c-3063c00b9855",
  statusLabel: "New",
  showings: 2,
  status: "new",
  transactionType: "shortsale",
  initialListPrice: 2,
  listPrice: 0,
  entityStatusAssociation: "closing",
  conforming: "yes",
  securitizedAsset: "no",
  distressedAsset: false,
  photoStatus: undefined,
  photoStatusLabel: undefined,
  serviceLevel: undefined,
  serviceLevelLabel: undefined,
  yardSignRemovedDate: undefined,
  sellerEntityId: "f7fc571f-7b59-4e2a-ba81-83ada638aa00",
  fieldVisitRequestedDate: "2024-05-14",
  fieldVisitCompletedDate: "2024-05-14",
  intakeDate: "2024-05-27",
  projectedEnteraAccessDate: "2024-05-27",
  actualEnteraAccessDate: "2024-05-27",
  expectedListDate: "2024-05-27",
  onMarketDate: "2024-05-27",
  listingAgreementDate: "2024-05-27",
  mustSellByDate: "2024-05-27",
  originalListingDate: "2024-05-27",
  listingExpirationDate: "2024-05-27",
  yardSignInstallationDate: "2024-05-27",
  offerPeriodEndDate: "2024-05-27",
  proPhotosUpdatedDate: "2024-05-27",
  propertyConditionPhotoLink: "https://ancient-loophole.biz",
  propertyConditionVideoLink: "https://warmhearted-detour.net/",
  propertyConditionNotes: "delinquo dolorem admoveo deripio cunctatio",
  sellerDispoIdentifier: "aeneus absconditus coniuratio sol vehemens",
  yardSignStatus: "removed",
  cancellationDate: "2024-05-27",
  cancellationReason: "entera_fees",
  cancellationNote: "infit distinctio ciminatio comminor angelus",
  listingTerminationDate: "2024-05-27",
  listingTerminationReason: "selling_in_portfolio",
  listingTerminationReasonNote: "arbitro careo solus umquam autem",
  evaluationInputs: [],
  evaluationAttributes: {
    price: 2,
    dueDate: null,
    requestDate: null,
    completionDate: null,
    blockDate: "2024-05-27",
    blockReason: "inaccessible",
    blockReasonNote: "quo sollers color bis sufficio",
    enteraEvaluationLink: "https://qualified-layer.biz/",
  },
  accessAttributes: {
    showingInstructions: "appointment_required",
    occupiedByTenant: true,
    vacancyDate: null,
    lockboxInstalledDate: "2024-05-14",
    lockboxRemovedDate: null,
    lockboxType: "supra",
    accessNotes: "concedo aveho adduco perferendis damnatio",
    showingCode: "tredecim aliquam terebro decretum ambitus",
    clientLockboxCode: "patria animadverto stipes adversus collum",
    lockboxSerialNumber: "cupiditate depromo aliquam vulgivagus venio",
    lastPropertyVisit: null,
    showingHoldDate: "2024-05-27",
    showingHoldReason: "tenant_in_place",
    showingHoldReasonNotes: "succurro vix ceno amaritudo culpo",
  },
  constructionAttributes: {
    inProgress: "no",
    estScopeAmount: "2.0",
    approvedScopeAmount: "4.0",
    completionEst: "2024-05-27",
    actualCompletionDate: null,
    note: "arbustum argentum aspicio dolor curis",
  },
  mlsRecordsAttributes: [
    {
      id: "bc10b060-b54e-4649-a4eb-7a995606aa2c",
      mlsSourceId: "5cd3f188-f869-4740-9892-b0cce1157fe0",
      number: "S15DS485D",
      primary: true,
      status: "sold",
    },
  ],
  entityNames: [
    {
      id: "7b44596d-c40e-49a0-8ead-e7472c074d38",
      contractName: "AINO IN LLC",
      signatureBlock: "AINO IN LLC",
      status: "active",
      sellerId: "5e70b818-ab86-47d7-ae2c-3063c00b9855",
    },
    {
      id: "e2d69731-053a-46c5-ac55-b7416b728e86",
      contractName: "AR Leasing Company",
      signatureBlock: "AR Leasing Company",
      status: "active",
      sellerId: "5e70b818-ab86-47d7-ae2c-3063c00b9855",
    },
    {
      id: "f7fc571f-7b59-4e2a-ba81-83ada638aa00",
      contractName: "Brian Test Entity Name",
      signatureBlock: "Brian Test Entity",
      status: "active",
      sellerId: "5e70b818-ab86-47d7-ae2c-3063c00b9855",
    },
  ],
};

export const listingDetailsOptions = {
  blockReasons: [
    { value: "squatters", label: "Squatters" },
    { value: "inaccessible", label: "Inaccessible" },
    { value: "missing_keys", label: "Missing keys" },
    { value: "tenant_in_place", label: "Tenant in place" },
    { value: "health_and_safety", label: "Health & safety" },
  ],
  cancellationReasons: [
    {
      value: "excessive_rehab_peril_event",
      label: "Excessive Rehab/Peril Event",
    },
    { value: "squatters", label: "Squatters" },
    { value: "selling_in_portfolio", label: "Selling in Portfolio" },
    { value: "entera_agents", label: "Entera Agents" },
    { value: "entera_processes", label: "Entera Processes" },
    { value: "entera_fees", label: "Entera Fees" },
    { value: "leasing_vs_selling", label: "Leasing vs. Selling" },
    {
      value: "unwanted_financial_impact_of_sale_offers_too_low",
      label: "Unwanted Financial Impact of Sale/Offers too low",
    },
    { value: "hoa_sale_restriction", label: "HOA Sale Restriction" },
    { value: "reit_implications", label: "REIT Implications" },
    { value: "tax_implications", label: "Tax Implications" },
    { value: "firpta", label: "FIRPTA" },
    { value: "other", label: "Other" },
  ],
  conformings: [
    { value: "yes", label: "Yes" },
    { value: "no", label: "No" },
    { value: "pending", label: "Pending" },
  ],
  constructionInProgress: [
    { value: "yes", label: "Yes" },
    { value: "no", label: "No" },
    { value: "unsure", label: "Unsure" },
    { value: "completed", label: "Completed" },
  ],
  entityStatusAssociations: [
    { value: "listing_agreement", label: "Listing Agreement" },
    { value: "closing", label: "Closing" },
  ],
  evaluationInputs: [
    { value: "photos", label: "Photos" },
    { value: "videos", label: "Videos" },
    { value: "meta_data", label: "Meta Data" },
    { value: "field_evaluation", label: "Field Evaluation" },
  ],
  listingTerminationReasons: [
    {
      value: "excessive_rehab_peril_event",
      label: "Excessive Rehab/Peril Event",
    },
    { value: "squatters", label: "Squatters" },
    { value: "selling_in_portfolio", label: "Selling in Portfolio" },
    { value: "entera_agents", label: "Entera Agents" },
    { value: "entera_processes", label: "Entera Processes" },
    { value: "entera_fees", label: "Entera Fees" },
    { value: "leasing_vs_selling", label: "Leasing vs. Selling" },
    {
      value: "unwanted_financial_impact_of_sale_offers_too_low",
      label: "Unwanted Financial Impact of Sale/Offers too low",
    },
    { value: "hoa_sale_restriction", label: "HOA Sale Restriction" },
    { value: "reit_implications", label: "REIT Implications" },
    { value: "tax_implications", label: "Tax Implications" },
    { value: "firpta", label: "FIRPTA" },
    { value: "other", label: "Other" },
  ],
  lockboxTypes: [
    { value: "combo", label: "Combo" },
    { value: "supra", label: "Supra" },
    { value: "sentry", label: "Sentry" },
    { value: "rently", label: "Rently" },
    { value: "keypad", label: "KeyPad" },
    { value: "other", label: "Other" },
  ],
  mlsSources: [
    {
      id: "09c428c4-a5c8-4b6e-97f7-ff6df74e7dbd",
      name: "AINCAR",
      mlsUrl: null,
    },
    {
      id: "535a4de6-ba5b-41bb-b41d-ae265607835b",
      name: "ARMLS",
      mlsUrl: null,
    },
    {
      id: "678f3e06-5bbd-4014-99ee-515ceb2f16d5",
      name: "canopygrid",
      mlsUrl: "https://login.canopymls.com/idp/login/canopyrealtors",
    },
    {
      id: "bbccc7e1-9147-425c-ae70-57e6173a4015",
      name: "CBRMLS",
      mlsUrl: "https://cr.flexmls.com/ticket/login",
    },
    {
      id: "7c22e6c4-b1e9-4011-b2d5-32078053b8ea",
      name: "Charleston Trident",
      mlsUrl: null,
    },
    {
      id: "1ad0ae55-12cf-4df2-822f-2e86cfcf4ef6",
      name: "CincyMLS",
      mlsUrl:
        "https://sso.tangilla.com/auth/realms/6560/protocol/openid-connect/auth?client_id=cabr-member-portal&scope=openid&response_type=code&redirect_uri=https%3A%2F%2Fportal.cabr.org%2Fauth%2Fcallback&state=YAZsq2hkJ9G1eCUQqIbeb0E3MwNI2o_4rwDRwFN6MzQ&nonce=974038",
    },
    {
      id: "2d761cc1-8700-4a2e-85db-21882268ab16",
      name: "DABR",
      mlsUrl: null,
    },
    {
      id: "5cd3f188-f869-4740-9892-b0cce1157fe0",
      name: "DTON",
      mlsUrl: null,
    },
    {
      id: "526658ae-09e2-42d0-9403-3f5c0776349c",
      name: "fmls",
      mlsUrl:
        "https://login.fmls.com/samlsp?redirectUrl=https://www.fmls.com/memberhome",
    },
    {
      id: "742bdb63-d0bb-4b97-aee2-e5a00cc05a74",
      name: "galmls",
      mlsUrl: "https://galmls.paragonrels.com/ParagonLS/Default.mvc/Login",
    },
    {
      id: "89bf8e79-792c-4023-b677-da3596bae405",
      name: "gamls",
      mlsUrl: "https://www.gamls.com/",
    },
    {
      id: "6bac7f4b-73bb-48bc-8e87-452fc0ef4353",
      name: "glvar",
      mlsUrl: "https://glvar.clareityiam.net/idp/login",
    },
    {
      id: "49d6fd70-04c3-4c62-bd83-5bf51a2bbf32",
      name: "har",
      mlsUrl: "https://www.har.com/login",
    },
    {
      id: "c3ebf576-a878-43a6-84df-fd2d59ea1119",
      name: "Heartland",
      mlsUrl: "https://heartland.clareityiam.net/idp/login",
    },
    {
      id: "c5b6d7b7-8405-4ced-a08e-13c6e1b45174",
      name: "MAAR",
      mlsUrl: "https://maar.paragonrels.com/ParagonLS/Default.mvc/Login",
    },
    {
      id: "7650c033-a050-4de8-a78b-3cd3b5f98368",
      name: "MAR",
      mlsUrl: null,
    },
    {
      id: "5935f6ec-0a2f-4a1c-aec2-5ab346676615",
      name: "marisgrid",
      mlsUrl: "https://marismls.com/sso/saml2/login/p/1",
    },
    {
      id: "c26329ab-d7ab-4217-8671-abeb7d84a314",
      name: "miborgrid",
      mlsUrl:
        "https://auth.mibor.com/login?ReturnUrl=https%3a%2f%2fmember.mibor.com/en-us",
    },
    {
      id: "2a6d7e1e-3616-4330-986a-63dd64faeea4",
      name: "MLSOK",
      mlsUrl: null,
    },
    {
      id: "2b93afe0-4a66-43a6-b5ff-97b7207ebedd",
      name: "MLSSAZ",
      mlsUrl: null,
    },
    {
      id: "6f02b5db-ed52-49c7-bcae-8960e2985f2e",
      name: "MLS Technology",
      mlsUrl: null,
    },
    {
      id: "817af5a1-046e-4651-9a16-3bf556400794",
      name: "MLS United",
      mlsUrl: null,
    },
    {
      id: "f5e79ed1-160f-42c7-beb6-f413fd17a910",
      name: "nefar",
      mlsUrl: "https://members.flexmls.com/ticket",
    },
    {
      id: "ee13b74e-dcd3-4aa8-a486-f88263bf6a00",
      name: "NKMLS",
      mlsUrl: null,
    },
    {
      id: "5bfb933a-9471-4b71-8963-7c6c2f3866a2",
      name: "NorthStar ",
      mlsUrl: null,
    },
    {
      id: "2529ae57-f6b9-4215-844e-accd427b9e95",
      name: "NortStar",
      mlsUrl: null,
    },
    {
      id: "5685d613-c43c-433e-ab9e-ce5eb0819358",
      name: "ntreis",
      mlsUrl: null,
    },
    {
      id: "6f3dc298-8e92-4780-8fd0-748ed7ba23f5",
      name: "Real",
      mlsUrl: null,
    },
    {
      id: "09e15fe9-a626-470d-b747-5fc48253743a",
      name: "SABOR",
      mlsUrl: "https://api-sabor.connectmls.com/sso/login",
    },
    {
      id: "90cebf6c-82f2-450e-8e10-bf3319d63f2d",
      name: "Stellar",
      mlsUrl: "https://central.stellarmls.com/",
    },
    {
      id: "17edf40b-ff68-4b70-92db-4e689e2dda61",
      name: "SWFLMLS",
      mlsUrl: "https://swflmls.clareityiam.net/idp/login",
    },
    {
      id: "4cc626b6-9831-4bb6-b48e-e6011c422c43",
      name: "trianglemls",
      mlsUrl: null,
    },
  ],
  mlsStatuses: [
    { value: "active", label: "Active" },
    { value: "draft", label: "Draft" },
    { value: "expired", label: "Expired" },
    { value: "pending", label: "Pending" },
    { value: "sold", label: "Sold" },
    {
      value: "temporarily_off_market",
      label: "Temporarily Off Market",
    },
    { value: "terminated", label: "Terminated" },
    { value: "withdrawn", label: "Withdrawn" },
  ],
  photoStatuses: [
    { value: "no_photos", label: "No Photos" },
    { value: "basic_photos", label: "Basic Photos" },
    { value: "pro_photos_ordered", label: "Pro Photos Ordered" },
    { value: "pro_photos_received", label: "Pro Photos Received" },
    {
      value: "pro_photos_on_active_listing",
      label: "Pro Photos on Active Listing",
    },
  ],
  securitizedAssets: [
    { value: "yes", label: "Yes" },
    { value: "no", label: "No" },
    { value: "tbd", label: "TBD" },
  ],
  sellersForNewListings: [
    {
      id: "e6fab921-87e8-478e-811c-dbc3fa005d36",
      name: "AMH 4-25",
      "integrated?": false,
    },
    {
      id: "bc752b85-93ad-4cf2-8324-af32d4c3a41c",
      name: "Barrows and Sons",
      "integrated?": false,
    },
    {
      id: "67c5073c-5715-4feb-a1aa-183dc4c406d0",
      name: "Bridge Investment Group",
      "integrated?": false,
    },
    {
      id: "67495b89-90aa-4653-870c-edbeade35954",
      name: "Center Creek",
      "integrated?": false,
    },
    {
      id: "107b9447-5d68-4626-830f-372ea391b8b3",
      name: "Entry Homes",
      "integrated?": false,
    },
    {
      id: "5893dcc3-6e40-46d6-8b5f-1da4a0a4834f",
      name: "FAKE AMH",
      "integrated?": false,
    },
    {
      id: "0fc952bc-a9b2-491f-8fc7-2e5e0646ba0b",
      name: "FK 4-25",
      "integrated?": false,
    },
    {
      id: "383914e4-6739-4cdd-af82-7923356bca0d",
      name: "FKH 4-30",
      "integrated?": false,
    },
    {
      id: "3cef6f18-bcd2-4310-a0d1-018494b6c3e7",
      name: "FKH 4-30 v2",
      "integrated?": false,
    },
    {
      id: "7a5c7e76-d5fa-4cd3-8c41-af916cbedebb",
      name: "FKH Combo",
      "integrated?": false,
    },
    {
      id: "c602b42e-a5d1-44d3-9b4a-70b2c239b6ed",
      name: "FKH combo 2",
      "integrated?": false,
    },
    {
      id: "62c1ed83-131b-4350-94f9-a7605ff4d885",
      name: "FKH t2",
      "integrated?": false,
    },
    {
      id: "4f45b614-fb99-4993-a640-2f169677302e",
      name: "FKH t3a",
      "integrated?": false,
    },
    {
      id: "32d21575-2782-49ff-bb16-eb7532c65b2a",
      name: "FKH t4",
      "integrated?": false,
    },
    {
      id: "011b7f72-84fb-4f1f-a591-f08496d211eb",
      name: "Gottlieb, Koepp and Cruickshank",
      "integrated?": false,
    },
    {
      id: "18e8f1a5-13f6-49f2-b287-02ae2808179d",
      name: "Greenholt-Wolff",
      "integrated?": false,
    },
    {
      id: "f2ba0ceb-8cc4-4874-bfba-d9e088014262",
      name: "HH 4-25",
      "integrated?": false,
    },
    {
      id: "7ac84d84-f43a-4f54-a98b-64c7642f7fd5",
      name: "IH 4-25",
      "integrated?": false,
    },
    {
      id: "5e70b818-ab86-47d7-ae2c-3063c00b9855",
      name: "Internal Entera",
      "integrated?": false,
    },
    {
      id: "fd534927-80f9-4e84-9cff-9a571f2b82fb",
      name: "Invitation Homes",
      "integrated?": false,
    },
    {
      id: "af8b5455-30b4-4a4a-965a-774c12d64b6a",
      name: "lafayette 4-25",
      "integrated?": false,
    },
    {
      id: "6d102459-fc65-4559-97e2-c105e9a5dce8",
      name: "Man 4-10",
      "integrated?": false,
    },
    {
      id: "ee7b1c4e-3325-4d9e-b8b4-ee5133670520",
      name: "Man 4-10 new",
      "integrated?": false,
    },
    {
      id: "34a24eda-36ea-499a-92f1-87934b08e5fa",
      name: "man 4-25",
      "integrated?": false,
    },
    {
      id: "0d44b944-dddb-43df-9545-d7b099790a1f",
      name: "Man Group",
      "integrated?": false,
    },
    {
      id: "71ca19be-4041-4867-bd84-5803a8574888",
      name: "Man Migration",
      "integrated?": false,
    },
    {
      id: "5b8e713a-f262-4b69-a09a-a934b245727d",
      name: "promise 4-25",
      "integrated?": false,
    },
    {
      id: "73499e68-5f29-4e2a-9b44-0581d3818322",
      name: "Promise Homes",
      "integrated?": false,
    },
    {
      id: "6e8c415f-9d05-4486-9bdf-b3ecdb5bcd01",
      name: "Rithm",
      "integrated?": false,
    },
    {
      id: "9da9b3f7-04bc-494f-923f-9461cc393e9c",
      name: "rithm 4-25",
      "integrated?": false,
    },
    {
      id: "3961e3ac-b241-4aa0-8da4-67bb35253672",
      name: "Shields-Hagenes",
      "integrated?": false,
    },
  ],
  serviceLevels: [
    { value: "listing", label: "Listing" },
    { value: "make_ready", label: "Make Ready" },
    { value: "btr", label: "BTR" },
    {
      value: "listing_full_service_closing",
      label: "Listing - Full Service Closing",
    },
    {
      value: "make_ready_full_service_closing",
      label: "Make Ready - Full Service Closing",
    },
  ],
  showingHoldReasons: [
    { value: "squatters", label: "Squatters" },
    { value: "inaccessible", label: "Inaccessible" },
    { value: "missing_keys", label: "Missing keys" },
    { value: "tenant_in_place", label: "Tenant in place" },
    { value: "health_and_safety", label: "Health & safety" },
    {
      value: "waiting_on_lockbox_and_keys",
      label: "Waiting on Lockbox & Keys",
    },
    { value: "seller_requested", label: "Seller Requested" },
  ],
  showingInstructions: [
    { value: "go_and_show", label: "Go and Show" },
    { value: "appointment_required", label: "Appointment Required" },
    { value: "no_showings", label: "No Showings" },
  ],
  transactionTypes: [
    { value: "traditional", label: "Traditional Sale" },
    { value: "direct_to_tenant", label: "Direct to Tenant" },
    { value: "shortsale", label: "Shortsale" },
    { value: "reo", label: "REO" },
    { value: "auction", label: "Auction" },
  ],
  usStates: [
    { abbreviation: "AL", name: "Alabama" },
    { abbreviation: "AK", name: "Alaska" },
    { abbreviation: "AS", name: "American Samoa" },
    { abbreviation: "AZ", name: "Arizona" },
    { abbreviation: "AR", name: "Arkansas" },
    { abbreviation: "CA", name: "California" },
    { abbreviation: "CO", name: "Colorado" },
    { abbreviation: "CT", name: "Connecticut" },
    { abbreviation: "DE", name: "Delaware" },
    { abbreviation: "DC", name: "District Of Columbia" },
    { abbreviation: "FM", name: "Federated States Of Micronesia" },
    { abbreviation: "FL", name: "Florida" },
    { abbreviation: "GA", name: "Georgia" },
    { abbreviation: "GU", name: "Guam" },
    { abbreviation: "HI", name: "Hawaii" },
    { abbreviation: "ID", name: "Idaho" },
    { abbreviation: "IL", name: "Illinois" },
    { abbreviation: "IN", name: "Indiana" },
    { abbreviation: "IA", name: "Iowa" },
    { abbreviation: "KS", name: "Kansas" },
    { abbreviation: "KY", name: "Kentucky" },
    { abbreviation: "LA", name: "Louisiana" },
    { abbreviation: "ME", name: "Maine" },
    { abbreviation: "MH", name: "Marshall Islands" },
    { abbreviation: "MD", name: "Maryland" },
    { abbreviation: "MA", name: "Massachusetts" },
    { abbreviation: "MI", name: "Michigan" },
    { abbreviation: "MN", name: "Minnesota" },
    { abbreviation: "MS", name: "Mississippi" },
    { abbreviation: "MO", name: "Missouri" },
    { abbreviation: "MT", name: "Montana" },
    { abbreviation: "NE", name: "Nebraska" },
    { abbreviation: "NV", name: "Nevada" },
    { abbreviation: "NH", name: "New Hampshire" },
    { abbreviation: "NJ", name: "New Jersey" },
    { abbreviation: "NM", name: "New Mexico" },
    { abbreviation: "NY", name: "New York" },
    { abbreviation: "NC", name: "North Carolina" },
    { abbreviation: "ND", name: "North Dakota" },
    { abbreviation: "MP", name: "Northern Mariana Islands" },
    { abbreviation: "OH", name: "Ohio" },
    { abbreviation: "OK", name: "Oklahoma" },
    { abbreviation: "OR", name: "Oregon" },
    { abbreviation: "PW", name: "Palau" },
    { abbreviation: "PA", name: "Pennsylvania" },
    { abbreviation: "PR", name: "Puerto Rico" },
    { abbreviation: "RI", name: "Rhode Island" },
    { abbreviation: "SC", name: "South Carolina" },
    { abbreviation: "SD", name: "South Dakota" },
    { abbreviation: "TN", name: "Tennessee" },
    { abbreviation: "TX", name: "Texas" },
    { abbreviation: "UT", name: "Utah" },
    { abbreviation: "VT", name: "Vermont" },
    { abbreviation: "VI", name: "Virgin Islands" },
    { abbreviation: "VA", name: "Virginia" },
    { abbreviation: "WA", name: "Washington" },
    { abbreviation: "WV", name: "West Virginia" },
    { abbreviation: "WI", name: "Wisconsin" },
    { abbreviation: "WY", name: "Wyoming" },
  ],
  yardSignStatuses: [
    { value: "install_ordered", label: "Install Ordered" },
    { value: "installed", label: "Installed" },
    { value: "removed", label: "Removed" },
    { value: "no_sign_hoa", label: "No Sign Permitted (HOA)" },
    { value: "no_sign", label: "No Sign" },
    { value: "no_sign_needed", label: "No Sign Needed" },
  ],
};
